name       : pelican
version    : 3.7.1
release    : 1
source     :
    - https://github.com/getpelican/pelican/archive/3.7.1.tar.gz : 81e1c8492d6491b7a637525eda6a0840ee36d2ce11c54233419b3661ce4d5c80
license    : GPL-3.0 
component  : programming.python
summary    : Pelican is a static site generator
description: |
    SPelican is a static site generator written in Pythin that supports Markdown and reST syntax
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
