name       : cartopy
version    : 0.15.0
release    : 1
source     :
    - https://github.com/SciTools/cartopy/archive/v0.15.0.tar.gz : fdee52cc2f259785a7744951ba43f339d33d517a5ec9cee301a33a267c60fd65
license    : LGPL-3.0
component  : programming.python
summary    : a cartographic python library with matplotlib support
description: |
    Cartopy is a Python package designed to make drawing maps for data analysis and visualisation easy.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
    - numpy
    - cython
    - geos
    - pkgconfig(proj)
    - python-six
    - shapely
    - pyshp
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install