name       : python-igraph
version    : 0.7.0
release    : 1
source     :
    - https://github.com/igraph/python-igraph/releases/download/0.7.0/python-igraph-0.7.0.tar.gz : 64ac270e80a92066d489407be1900a329df8e26844430f941ecc88771188c471
license    : GPL-2.0 
component  : programming.python
summary    : Python interface for igraph 
description: |
    igraph is a library for creating and manipulating graphs. It is intended to be as powerful (ie. fast) as possible to enable the analysis of large graphs
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
    - pkgconfig(igraph)
setup      : |
    %python_setup
    %python3_setup 
install    : |
    %python_install
    %python3_install 
