name       : networkx
version    : 1.11
release    : 1
source     :
    - https://github.com/networkx/networkx/archive/networkx-1.11.tar.gz : 5d630c369f6d77591f32d7d15d882ed5c9299f8ea084e6f0f6afea8b63b0f5ce
license    : BSD-3-clause
component  : programming.python
summary    : NetworkX is a Python package for complex networks
description: |
    NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.
builddeps  : 
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup    
install    : |
    %python_install
    %python3_install

