name       : pyshp
version    : 1.2.10
release    : 1
source     :
    - https://github.com/GeospatialPython/pyshp/archive/1.2.10.tar.gz : 009e02b281d7f509c34d31aca3545334e45bea15136f3bb81a37b4d13e21f9bd
license    : MIT
component  : programming.python
summary    : This library reads and writes ESRI Shapefiles in pure Python
description: |
    The Python Shapefile Library (pyshp) reads and writes ESRI Shapefiles in pure Python
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

